### ISSUE TITLE
지도 상단 영역 - 캘린더, 장소 검색

### ISSUE THREAD

**Issue by devSoyoung** [Nugux/Nugux-fe#1]
## TODO
* 캘린더에서 출발 날짜 - 도착날짜 선택하면 API 호출 (하는 척 하기) > 논의 필요
* 달력 한글화 및 모바일 화면 최적화
* 달력 날짜 표시되는 영역 모바일 화면 안에 들어오게 수정
* 토글 버튼 추가하고 검색/캘린더 전환할 수 있도록 수정

**Comment by devSoyoung** [comment]
@Lee-WonJun  @90Byte  @dream365 
생각해보니까 출발 - 도착이 필요없을 것 같지 않습니까 선배님들
서버에서 어차피 특정 날짜 하루만 파라미터로 받을거죠?

**Comment by Lee-WonJun** [comment]
특정날짜 하루만 하는게 좋을듯 합니다.
