### ISSUE TITLE
프론트엔드 개발 과제

### ISSUE THREAD

**Issue by devSoyoung** [Nugux/Nugux-fe#3]
빠진거/완료한거 추가 체크 부탁드립니다 🙏🏻

## 작업목록
- [ ] ~~캘린더 한글화~~
- [ ] ~~여행할 지역 선택하는 페이지 추가~~

### 지도 작업목록
- [x] 날짜 선택 시 API 요청(params: lat, lng, zoom-level, date)
- [x] 지도에서 위치 이동 시 해당 위치정보로 API 재요청
- [x] 요청 결과 마커로 지도에 표시하기

### 상세페이지 작업목록
- [x] 마커 선택 시 해당 여행지 정보 가져와서 보여주기

**Comment by Lee-WonJun** [comment]
@Lee-WonJun @dream365 @90Byte
